export {default as NavBar} from './NavBar/NavBar'
export {default as MiniTitle} from './Minititle/MiniTitle'
export {default as Subtitle} from './Subtitle/Subtitle'
export {default as Paragraph} from './Paragraph/Paragraph'
export {default as ProfessionalName} from './ProfessionalName/ProfessionalName'
export {default as ProfessionalLogo} from './ProfessionalLogo/ProfessionalLogo'
